document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="patient-video.css">');

const connectionText = document.querySelector('#connectionText');
const stateText = document.querySelector('#participantState');
const roomTimer = document.querySelector('#roomTimer');
const localVideo = document.querySelector('#localVideo');
const remoteVideo = document.querySelector('#remoteVideo');
const localFeed = document.querySelector('#localFeed');
const remoteFeed = document.querySelector('#remoteFeed');
const micButton = document.querySelector('#mic');
const cameraButton = document.querySelector('#camera');
const screenButton = document.querySelector('#screen');
const documentSyncStatus = document.querySelector('#documentSyncStatus');
const documentEditorLabel = document.querySelector('#documentEditorLabel');
const documentFields = [...document.querySelectorAll('[data-doc-field]')];
const voiceButtons = [...document.querySelectorAll('[data-voice-field]')];
const voiceStatus = document.querySelector('#voiceStatus');

let viewer = 'patient';
let localStream = new MediaStream();
let remoteStream = new MediaStream();
let peer = null;
let iceServers = [{ urls: 'stun:stun.l.google.com:19302' }];
let pendingCandidates = [];
let lastRevision = -1;
let offerInFlight = false;
let pollTimer = null;
let signalTimer = null;
let timer = null;
let screenTrack = null;
let leaving = false;
let docClock = 0;
let docSyncRequestedForRevision = -1;
let recognition = null;
let voiceField = null;
let voiceBaseValue = '';
const docVersions = new Map(documentFields.map((field) => [field.dataset.docField, { counter: 0, actor: '' }]));
const docDebounce = new Map();

function roomApi(action, extra = {}) { return fetch('/api/video/room', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...extra }) }).then(parseJson); }
async function parseJson(response) { const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Ошибка запроса'); return body; }
function setParticipantLabels() { const doctor = viewer === 'doctor'; document.querySelector('#localName').textContent = doctor ? 'Анна Крылова (вы)' : 'Елена Смирнова (вы)'; document.querySelector('#localRole').textContent = doctor ? 'Врач · локальное видео' : 'Пациент · локальное видео'; document.querySelector('#remoteName').textContent = doctor ? 'Елена Смирнова' : 'Анна Крылова'; document.querySelector('#remoteRole').textContent = doctor ? 'Пациент' : 'Врач · удаленное видео'; documentEditorLabel.textContent = doctor ? 'Вы редактируете как врач' : 'Вы редактируете как пациент'; }
async function sendSignal(type, payload) { const target = viewer === 'doctor' ? 'patient' : 'doctor'; await parseJson(await fetch('/api/video/signals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ target, type, payload }) })); }
function setDocumentStatus(text, state = '') { documentSyncStatus.className = `document-sync-status ${state}`.trim(); documentSyncStatus.innerHTML = `<span></span>${text}`; }
function compareVersion(left, right) { if ((left?.counter || 0) !== (right?.counter || 0)) return (left?.counter || 0) - (right?.counter || 0); return String(left?.actor || '').localeCompare(String(right?.actor || '')); }
function documentSnapshot() { const fields = {}; for (const field of documentFields) { const key = field.dataset.docField; fields[key] = { value: field.value, version: docVersions.get(key) || { counter: 0, actor: '' } }; } return fields; }
async function sendDocumentMessage(message) { await sendSignal('ice', { __medlinkSharedDocument: true, ...message }); }
function applyRemoteField(key, value, version, editorRole) { const field = documentFields.find((item) => item.dataset.docField === key); if (!field) return; const currentVersion = docVersions.get(key) || { counter: 0, actor: '' }; if (compareVersion(version, currentVersion) <= 0) return; docVersions.set(key, version); docClock = Math.max(docClock, Number(version.counter) || 0); field.value = String(value ?? ''); field.classList.remove('remote-update'); void field.offsetWidth; field.classList.add('remote-update'); setTimeout(() => field.classList.remove('remote-update'), 700); setDocumentStatus(editorRole === 'doctor' ? 'Обновлено врачом' : 'Обновлено пациентом', 'remote'); }
async function handleDocumentMessage(payload) { if (payload.messageType === 'request') { await sendDocumentMessage({ messageType: 'state', fields: documentSnapshot(), editorRole: viewer }); return; } if (payload.messageType === 'state' && payload.fields && typeof payload.fields === 'object') { for (const [key, entry] of Object.entries(payload.fields)) { if (entry && typeof entry === 'object') applyRemoteField(key, entry.value, entry.version || { counter: 0, actor: '' }, payload.editorRole); } setDocumentStatus('Документ синхронизирован', 'synced'); return; } if (payload.messageType === 'field') applyRemoteField(payload.field, payload.value, payload.version || { counter: 0, actor: '' }, payload.editorRole); }
function scheduleDocumentFieldSync(field) { const key = field.dataset.docField; docClock += 1; const version = { counter: docClock, actor: viewer }; docVersions.set(key, version); setDocumentStatus('Сохраняем изменения…', 'syncing'); clearTimeout(docDebounce.get(key)); docDebounce.set(key, setTimeout(async () => { try { await sendDocumentMessage({ messageType: 'field', field: key, value: field.value, version, editorRole: viewer }); setDocumentStatus('Изменения синхронизированы', 'synced'); } catch (error) { console.error(error); setDocumentStatus('Не удалось синхронизировать', 'syncing'); } }, 250)); }

function setVoiceStatus(text, state = '') { if (!voiceStatus) return; voiceStatus.textContent = text; voiceStatus.className = `voice-status ${state}`.trim(); }
function stopVoiceInput() { if (recognition) recognition.stop(); }
function initVoiceInput() {
  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  if (!SpeechRecognition) { voiceButtons.forEach((button) => { button.disabled = true; button.title = 'Голосовой ввод не поддерживается этим браузером'; }); setVoiceStatus('Голосовой ввод не поддерживается этим браузером', 'error'); return; }
  recognition = new SpeechRecognition(); recognition.lang = 'ru-RU'; recognition.continuous = true; recognition.interimResults = true;
  recognition.onstart = () => { voiceButtons.forEach((button) => button.classList.toggle('listening', button.dataset.voiceField === voiceField?.dataset.docField)); setVoiceStatus('Слушаю… говорите по-русски. Нажмите микрофон ещё раз, чтобы остановить.', 'listening'); };
  recognition.onresult = (event) => { if (!voiceField) return; let finalText = ''; let interimText = ''; for (let i = event.resultIndex; i < event.results.length; i += 1) { const text = event.results[i][0].transcript.trim(); if (event.results[i].isFinal) finalText += `${text} `; else interimText += text; } if (finalText) { const separator = voiceBaseValue && !/\s$/.test(voiceBaseValue) ? ' ' : ''; voiceBaseValue = `${voiceBaseValue}${separator}${finalText}`.slice(0, voiceField.maxLength || 4000); voiceField.value = voiceBaseValue; voiceField.dispatchEvent(new Event('input', { bubbles: true })); } else if (interimText) { const separator = voiceBaseValue && !/\s$/.test(voiceBaseValue) ? ' ' : ''; voiceField.value = `${voiceBaseValue}${separator}${interimText}`.slice(0, voiceField.maxLength || 4000); } };
  recognition.onerror = (event) => { const messages = { 'not-allowed': 'Разрешите браузеру доступ к микрофону для диктовки', 'audio-capture': 'Микрофон недоступен', 'no-speech': 'Речь не распознана — попробуйте ещё раз', network: 'Сервис распознавания речи недоступен' }; setVoiceStatus(messages[event.error] || 'Ошибка голосового ввода', 'error'); };
  recognition.onend = () => { voiceButtons.forEach((button) => button.classList.remove('listening')); if (voiceField) { voiceField.value = voiceBaseValue; scheduleDocumentFieldSync(voiceField); } voiceField = null; setVoiceStatus('Голосовой ввод остановлен'); };
  voiceButtons.forEach((button) => button.addEventListener('click', () => { const target = documentFields.find((field) => field.dataset.docField === button.dataset.voiceField); if (!target) return; if (voiceField) { stopVoiceInput(); return; } voiceField = target; voiceBaseValue = target.value; target.focus(); try { recognition.start(); } catch (error) { voiceField = null; setVoiceStatus('Не удалось запустить голосовой ввод', 'error'); } }));
}
function initDocumentEditing() { for (const field of documentFields) field.addEventListener('input', () => scheduleDocumentFieldSync(field)); initVoiceInput(); }
function updateMediaButtons() { const audioTrack = localStream.getAudioTracks()[0]; const videoTrack = localStream.getVideoTracks()[0]; micButton.classList.toggle('muted', !audioTrack || !audioTrack.enabled); cameraButton.classList.toggle('muted', !videoTrack || !videoTrack.enabled); micButton.setAttribute('aria-pressed', String(Boolean(audioTrack && audioTrack.enabled))); cameraButton.setAttribute('aria-pressed', String(Boolean(videoTrack && videoTrack.enabled))); localFeed.classList.toggle('has-video', Boolean(videoTrack && videoTrack.enabled)); }
async function acquireLocalMedia() { if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) throw new Error('Камера доступна только через HTTPS или localhost'); localStream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true, autoGainControl: true }, video: { width: { ideal: 1280 }, height: { ideal: 720 }, facingMode: 'user' } }); localVideo.srcObject = localStream; updateMediaButtons(); }
function closePeer() { if (peer) { peer.onicecandidate = null; peer.ontrack = null; peer.onconnectionstatechange = null; peer.close(); } peer = null; pendingCandidates = []; offerInFlight = false; remoteStream = new MediaStream(); remoteVideo.srcObject = null; remoteFeed.classList.remove('has-video'); }
function createPeer() { closePeer(); peer = new RTCPeerConnection({ iceServers }); localStream.getTracks().forEach((track) => peer.addTrack(track, localStream)); peer.onicecandidate = ({ candidate }) => { if (candidate) sendSignal('ice', candidate.toJSON()).catch(console.error); }; peer.ontrack = ({ track, streams }) => { const incoming = streams[0]; if (incoming) remoteVideo.srcObject = incoming; else { remoteStream.addTrack(track); remoteVideo.srcObject = remoteStream; } remoteFeed.classList.add('has-video'); track.addEventListener('ended', () => { if (!remoteVideo.srcObject || remoteVideo.srcObject.getVideoTracks().every((item) => item.readyState === 'ended')) remoteFeed.classList.remove('has-video'); }); }; peer.onconnectionstatechange = () => { const state = peer && peer.connectionState; if (state === 'connected') { connectionText.textContent = 'Прямое WebRTC-соединение установлено'; stateText.textContent = 'Камера и микрофон передаются собеседнику'; } else if (state === 'connecting') connectionText.textContent = 'Устанавливаем защищенное медиасоединение…'; else if (state === 'failed') { connectionText.textContent = 'Не удалось установить медиасоединение. Проверьте TURN-сервер'; offerInFlight = false; } else if (state === 'disconnected') { connectionText.textContent = 'Соединение прервано, пытаемся восстановить…'; offerInFlight = false; } }; }
async function flushCandidates() { if (!peer || !peer.remoteDescription) return; const queued = pendingCandidates.splice(0); for (const candidate of queued) { try { await peer.addIceCandidate(candidate); } catch (error) { console.error(error); } } }
async function createOffer() { if (viewer !== 'doctor' || !peer || offerInFlight || peer.signalingState !== 'stable') return; offerInFlight = true; const offer = await peer.createOffer(); await peer.setLocalDescription(offer); await sendSignal('offer', peer.localDescription.toJSON()); }
async function handleSignal(message) { if (message.type === 'ice' && message.payload && message.payload.__medlinkSharedDocument) { await handleDocumentMessage(message.payload); return; } if (!peer) createPeer(); if (message.type === 'offer') { await peer.setRemoteDescription(message.payload); await flushCandidates(); const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); await sendSignal('answer', peer.localDescription.toJSON()); return; } if (message.type === 'answer') { if (peer.signalingState === 'have-local-offer') { await peer.setRemoteDescription(message.payload); await flushCandidates(); offerInFlight = false; } return; } if (message.type === 'ice') { if (peer.remoteDescription) await peer.addIceCandidate(message.payload); else pendingCandidates.push(message.payload); } }
async function pollSignals() { const response = await parseJson(await fetch('/api/video/signals')); for (const message of response.messages) { try { await handleSignal(message); } catch (error) { console.error(error); if (!(message.type === 'ice' && message.payload && message.payload.__medlinkSharedDocument)) connectionText.textContent = 'Ошибка согласования WebRTC-соединения'; } } }
function renderRoom(room) { const both = room.doctorJoined && room.patientJoined; if (!both) { connectionText.textContent = viewer === 'doctor' ? 'Ожидание подключения пациента' : 'Ожидание подключения врача'; stateText.textContent = 'Видеоприем начнется после подключения обоих участников'; setDocumentStatus('Ожидание второго участника'); docSyncRequestedForRevision = -1; } else if (!peer || peer.connectionState === 'new') { connectionText.textContent = 'Оба участника в комнате, устанавливаем WebRTC-соединение…'; stateText.textContent = 'Согласование защищенного медиаканала'; } if (room.startedAt && !timer) timer = setInterval(() => { roomTimer.textContent = new Date(Math.max(0, Date.now() - room.startedAt)).toISOString().substring(14, 19); }, 1000); }
async function applyRoom(room, force = false) { renderRoom(room); const both = room.doctorJoined && room.patientJoined; const revisionChanged = room.revision !== lastRevision; if (revisionChanged) lastRevision = room.revision; if (!both) { if (peer && peer.connectionState !== 'new') createPeer(); return; } if (docSyncRequestedForRevision !== room.revision) { docSyncRequestedForRevision = room.revision; setDocumentStatus('Синхронизация документа…', 'syncing'); sendDocumentMessage({ messageType: 'request', editorRole: viewer }).catch(console.error); } if (force || revisionChanged || !peer || ['failed', 'closed'].includes(peer.connectionState)) createPeer(); if (viewer === 'doctor') await createOffer(); }
async function toggleMic() { const track = localStream.getAudioTracks()[0]; if (!track) return; track.enabled = !track.enabled; updateMediaButtons(); }
async function toggleCamera() { const track = localStream.getVideoTracks()[0]; if (!track) return; track.enabled = !track.enabled; updateMediaButtons(); }
async function stopScreenShare() { if (!screenTrack) return; const cameraTrack = localStream.getVideoTracks()[0]; const sender = peer && peer.getSenders().find((item) => item.track && item.track.kind === 'video'); if (sender && cameraTrack) await sender.replaceTrack(cameraTrack); screenTrack.onended = null; screenTrack.stop(); screenTrack = null; screenButton.classList.remove('muted'); localVideo.srcObject = localStream; updateMediaButtons(); }
async function toggleScreenShare() { if (screenTrack) { await stopScreenShare(); return; } if (!navigator.mediaDevices || !navigator.mediaDevices.getDisplayMedia) { connectionText.textContent = 'Демонстрация экрана не поддерживается этим браузером'; return; } try { const display = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: false }); screenTrack = display.getVideoTracks()[0]; const sender = peer && peer.getSenders().find((item) => item.track && item.track.kind === 'video'); if (sender) await sender.replaceTrack(screenTrack); localVideo.srcObject = display; localFeed.classList.add('has-video'); screenButton.classList.add('muted'); screenTrack.onended = () => stopScreenShare().catch(console.error); } catch (error) { if (error.name !== 'NotAllowedError') connectionText.textContent = 'Не удалось начать демонстрацию экрана'; } }
async function leaveRoom(action) { if (leaving) return; leaving = true; if (recognition && voiceField) recognition.stop(); clearInterval(pollTimer); clearInterval(signalTimer); for (const timerId of docDebounce.values()) clearTimeout(timerId); await stopScreenShare().catch(() => {}); localStream.getTracks().forEach((track) => track.stop()); closePeer(); await roomApi(action).catch(() => {}); window.location.href = viewer === 'doctor' ? '/doctor.html' : '/patient.html'; }
async function init() { const session = await parseJson(await fetch('/api/session')); viewer = session.role; if (!['doctor', 'patient'].includes(viewer)) { window.location.href = '/'; return; } setParticipantLabels(); initDocumentEditing(); try { await acquireLocalMedia(); } catch (error) { connectionText.textContent = error.message || 'Разрешите доступ к камере и микрофону'; localStream = new MediaStream(); updateMediaButtons(); } const config = await parseJson(await fetch('/api/video/ice-config')); iceServers = config.iceServers; createPeer(); const joinedRoom = await roomApi('join'); lastRevision = joinedRoom.revision; await applyRoom(joinedRoom, true); signalTimer = setInterval(() => pollSignals().catch(console.error), 350); pollTimer = setInterval(async () => { try { const room = await parseJson(await fetch('/api/video/room')); await applyRoom(room); } catch (error) { console.error(error); } }, 1000); }
micButton.addEventListener('click', toggleMic); cameraButton.addEventListener('click', toggleCamera); screenButton.addEventListener('click', toggleScreenShare); document.querySelector('#end').addEventListener('click', () => leaveRoom(viewer === 'doctor' ? 'end' : 'leave')); document.querySelector('#leave').addEventListener('click', () => leaveRoom('leave')); window.addEventListener('pagehide', () => { if (!leaving) fetch('/api/video/room', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'leave' }), keepalive: true }).catch(() => {}); });
init().catch((error) => { console.error(error); connectionText.textContent = 'Не удалось открыть видеоприем'; });
